<?xml version="1.0" encoding="utf-8"?><Database Name="Employ" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=Employ;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="EmployConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Employ" Member="Employs">
    <Type Name="Employ">
      <Column Name="Id" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Devepartment" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>